### ISSUE TITLE
pipx --global Installation Issue

### ISSUE THREAD

**Issue by BSuperbad** [pyOpenSci/python-package-guide#260]
**Describe the bug**

When trying to install pipx for macOS as a --global option, pipx's documentation is incorrect so we should add the note to the "tip" section. 
If installing on MacOS:

brew install pipx
pipx ensurepath
sudo pipx --global ensurepath  # optional to allow pipx actions with --global argument

Link: https://www.pyopensci.org/python-package-guide/tutorials/get-to-know-hatch.html#install-hatch

**How to reproduce**

$ sudo pipx ensurepath --global
usage: pipx [-h] [--quiet] [--verbose] [--global] [--version]
            {install,uninject,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,interpreter,run,runpip,ensurepath,environment,completions}
            ...
pipx: error: unrecognized arguments: --global

**Expected behavior**

We switched ensurepath and --global so that --global comes first and now it's good to go!

**Comment by ucodery** [comment]
A tip would be perfect here.

As long as we are providing out own tip, we should probably not promote this global option at all
```bash
brew install pipx
pipx ensurepath
```
will be enough for our users to get going.

**Comment by lwasser** [comment]
an update on this issue! a version of this issue was submitted by multiple people on different operating systems - phew! each having slightly different problems but related!

* issue https://github.com/pyOpenSci/python-package-guide/issues/271
* pr #278 

i think there was another issue but i can't seem to find it now. The solution here should be that we DON"T use pipx and instead run [hatch installer](https://hatch.pypa.io/latest/install/#installers) which should install on windows, mac and linux with no additional tools! i am going to create a new issue for this specific update and then link to all of the other issues including this one! 

this should be an easier way to get going with hatch. i had no idea that pipx would cause so many issues! thank you for this issue!!

**Comment by lwasser** [comment]
y'all - i've just [opened this pr which updates the installation instructions](https://github.com/pyOpenSci/python-package-guide/pull/308)  - if you are involved in multiple issues you'll see this same comment on all of them (i'm housekeeping)

A few things we learned chatting in #301  

1. the installers seem to be the way to go for windows and MAC (altho mac also supports homebrew install which people might have and prefer)
2. Hatch installs Python for you using UV if you don't have Python! so the installers provide an additional win of Python!

Reviews are welcome on my open PR!! we are teaching a workshop the week after next so i'll leave this open for a week with the plan to merge next tuesday July 2! this issue can then be closed! 🚀

**Comment by lwasser** [comment]
I am going to close this issue given we've moved to the hatch installers! if anyone thinks this should be reopened, please feel free to comment! thank you everyone for the thought put into the install process for Hatch!
