### ISSUE TITLE
[UX] Need "step 0: get Python and Hatch" on https://www.pyopensci.org/python-package-guide/tutorials/get-to-know-hatch.html

### ISSUE THREAD

**Issue by zackw** [pyOpenSci/python-package-guide#270]
People who aren't real familiar with what already comes with the OS, and what comes with core Python, may get stuck in step one of <https://www.pyopensci.org/python-package-guide/tutorials/get-to-know-hatch.html> when the recommended "pipx install hatch" command throws a "no such command `pipx`" error message.

Those instructions should come with a leader reminding people that they need to have Python installed in the first place, and then that Hatch is not part of core Python and needs to be installed itself.  As discussed face-to-face in the sprint, it may make sense to drop pipx entirely and just recommend "pip install hatch" for naive users.

(Related to #265)

**Comment by ofek** [comment]
My recommendation is for not requiring a manual Python installation at all and rather use one of the Hatch installers or binaries. I mentioned that in the blog post for 1.8 https://hatch.pypa.io/latest/blog/2023/12/11/hatch-v180/

Installation docs: https://hatch.pypa.io/latest/install/

**Comment by willingc** [comment]
Ooh cool @ofek. I didn't realize that there were installers now. Thanks!

**Comment by lwasser** [comment]
TODO: 

go to this tutorial - https://www.pyopensci.org/python-package-guide/tutorials/get-to-know-hatch.html - the first step is "pipx install hatch"

we should likely change this step to use the hatch installers which are detailed on [this page](https://hatch.pypa.io/latest/install/)

let's also include a small "note" on that page that links to @ofek [blog post](https://hatch.pypa.io/latest/blog/2023/12/11/hatch-v180/) on the hatch installers!

to add a note you'd use this syntax in our theme
```
Learn more about installing hatch using the hatch installers (which do not require python, pip or pipx to be preinstalled), [in this blog post](https://hatch.pypa.io/latest/blog/2023/12/11/hatch-v180/).  

This is also a very user friendly issue but we will need someone to test this installation out on windows FIRST before adding / revising the tutorial. we've already had people test it on mac successfully! 

We'd then want to remove any language about using pipx here. so much better / begginer friendly! thank you @ofek and everyone !! 🚀

**Comment by lwasser** [comment]
Friends - i believe we can close this issue
we have now 

✅ updated the tutorial page to specify using the installers rather than pipx (which removed singificant issues we were having!
✅ removed the discussion of installing python given Hatch will install for a user 
✅ we tested this approach yesterday in our second workshop (in person at scipy). everyone was able to get hatch installed. 

NOTE:there is a nuance with the installers where somtimes they will beging to download updates when a user runs hatch --version. this was a bit confusing so we may want to add a note about this behavior given it makes the user think that hatch is not installed yet. i will open a new issue about that soon but will close this issue for the time being as completed!

if anyone disagrees wtih this being completed please do feel free to reply here!! ✨ and we can reopen!
